#!/usr/bin/env bun
/**
 * Shared scaffolding for the generated example manifests (`examples-manifest.json` and
 * `examples-manifest-orm.json`): the `source` stamp (generating commit + content hash), the JSON
 * write and the repo-root path. Each generator owns its own entry shape + honesty check; this owns
 * the boilerplate around them, so the two manifests cannot drift in structure.
 */
import { execSync } from "node:child_process";
import { createHash } from "node:crypto";
import { writeFileSync } from "node:fs";
import { join } from "node:path";

/** The repo root (the `scripts/` dir's parent). */
const repoRoot = join(import.meta.dir, "..");

/** The generated-manifest envelope: a `source` stamp + a typed entry list. */
export interface GeneratedManifest<E> {
  $comment: string;
  source: { commit: string; hash: string };
  entries: E[];
}

/** Stamp, serialize and write one generated manifest; returns its `source` for the summary line. */
export function writeManifest<E>(options: {
  /** The output filename, relative to the repo root (e.g. `examples-manifest.json`). */
  readonly file: string;
  /** The generator's script name (used in `$comment` and the summary). */
  readonly generator: string;
  readonly entries: readonly E[];
}): { commit: string; hash: string } {
  const commit = execSync("git rev-parse HEAD").toString().trim();
  const hash = createHash("sha256")
    .update(JSON.stringify(options.entries))
    .digest("hex")
    .slice(0, 16);
  const manifest: GeneratedManifest<E> = {
    $comment: `GENERATED by scripts/${options.generator} — do not hand-edit. See packages/core/docs/EXAMPLE-COOKBOOK-CONVENTION.md.`,
    source: { commit, hash },
    entries: [...options.entries],
  };
  writeFileSync(join(repoRoot, options.file), `${JSON.stringify(manifest, null, 2)}\n`);
  return { commit, hash };
}
